import "./globals.css";
import Navbar from "@/components/Navbar";
import { Analytics } from "@vercel/analytics/react";
import BookingButton from "@/components/BookingButton";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="relative w-full h-fit flex flex-col justify-start items-center">
        <Navbar />
        <div className="fixed bottom-0 left-0 w-full block lg:hidden z-10">
          <BookingButton />
        </div>
        {children}
        <Analytics />
      </body>
    </html>
  );
}
